### ISSUE TITLE
rbind error

### ISSUE THREAD

**Issue by EBotes** [AnthonyRaborn/ShortForm#16]
Hi 

Not sure why, but I get the following error with this code:

```
library(ShortForm)
library(lavaan)
antModel = 'Boredom =~ FLLB1 + FLLB2 + FLLB3 + FLLB4 + FLLB5 + FLLB6 + 
                       FLLB8 + FLLB9 + FLLB10 + FLLB11 + FLLB13 + FLLB14 + 
                        FLLB15 + FLLB16 + FLLB17 + FLLB18 + FLLB19 + FLLB20 + 
                      FLLB21 + FLLB22 + FLLB23'


list.items <- list(c('FLLB1','FLLB2', 'FLLB3', 'FLLB4', 'FLLB5', 'FLLB6', 'FLLB8', 'FLLB9','FLLB10','FLLB11',
                   'FLLB13', 'FLLB14','FLLB15', 'FLLB16','FLLB17','FLLB18',
                 'FLLB19', 'FLLB20','FLLB21', 'FLLB22','FLLB23'))

  
BoredomShortForm = antcolony.lavaan(data = Shortform,ants = 20, evaporation = 0.7, 
                                  antModel =antModel, list.items = list.items, 
                              full = 21, i.per.f = 10, factors = 'Boredom', 
                                steps = 3, fit.indices = c('cfi','rmsea'), 
                                 fit.statistics.test = "(cfi > 0.9)&(rmsea < 0.08)", 
                               summaryfile = 'summary.txt', 
                                 feedbackfile ='iteration.html', max.run = 500) 
```
 **Run number 1 and ant number 20.           Error in rbind(summaryObject, matrix(c(as.numeric(antResults[[bestAnt,  : 
  number of columns of matrices must match (see arg 2)**

Any ideas as to why?

Not super experienced in R, so any help would be greatly appreciated!

**Comment by AnthonyRaborn** [comment]
Would you be able to share the data you're using with me (or at least a sufficiently similar data set if it's proprietary)?

**Comment by EBotes** [comment]
[Shortform.xlsx](https://github.com/AnthonyRaborn/ShortForm/files/11488899/Shortform.xlsx)
Thank you! Yes, gladly, have attached the file

**Comment by AnthonyRaborn** [comment]
Would you try the following steps for me?

1. Install the `bugfix` branch of ShortForm with one of the following commands:
`devtools::install_github('AnthonyRaborn/ShortForm', ref = 'bugfix')`
`remotes::install_github('AnthonyRaborn/ShortForm', ref = 'bugfix')`
(one of `devtools` or `remotes` needs to be installed)
2. Modify your `lavaan` model syntax in your script so there are no carriage returns/line breaks for the single factor
3. Re-run the modified script.

It _should_ work at this point. If you're getting errors still, or if the function runs to completion without producing a valid model, you can also try:
1. Increasing the `steps` parameter
2. Changing your fit statistic requirements (i.e., make the requirements more lenient)

I believe a combination of the above should fix the issue, but please let me know if you have the same or even another error even after these steps!

**Comment by EBotes** [comment]
Hi Anthony

Apologies for the long break between answers, I recently moved to a new university. I installed the devtools package, ran the bugfix, and removed the line break. The script now returns a new error:

Error in antcolony.lavaan(data = Sample1, ants = 5, evaporation = 0.7,  : 
  object 'best.so.far.fit.indices' not found

Not sure if this might be because an underlying package is missing. I changed laptops when moving so it might be that a package is not installed on the new laptop that was on the previous one?

Groete

Elouise


Code:

```
list.items <- list(c('FLLB1','FLLB2', 'FLLB3', 'FLLB4', 'FLLB5', 'FLLB6', 'FLLB8', 'FLLB9','FLLB10','FLLB11', 'FLLB13', 'FLLB14','FLLB15', 'FLLB16','FLLB17','FLLB18','FLLB19', 'FLLB20','FLLB21', 'FLLB22','FLLB23'))

BoredomShortForm <- antcolony.lavaan(
  data = Sample1,
  ants = 5, evaporation = 0.7, antModel = "Boredom =~ FLLB1 + FLLB2 + FLLB3 + FLLB4 + FLLB5 + FLLB6 + FLLB8 + FLLB9 + FLLB10 + FLLB11 + FLLB13 + FLLB14 + FLLB15 + FLLB16 + FLLB17 + FLLB18 + FLLB19 + FLLB20 + FLLB21 + FLLB22 + FLLB23",
  list.items = list.items, full = 21, i.per.f = 10,
  factors = "Boredom", steps = 3, fit.indices = c("cfi", "rmsea"),
  fit.statistics.test = "(cfi > 0.95)&(rmsea < 0.08)",
  summaryfile = "summary.txt",
  feedbackfile = "iteration.html",
  max.run = 500
)
```
 Run number 1 and ant number 5.           [1] "Compiling results."
Error in antcolony.lavaan(data = Sample1, ants = 5, evaporation = 0.7,  : 
  object 'best.so.far.fit.indices' not found

**Comment by AnthonyRaborn** [comment]
I've identified two issues that lead to this result.

1. An improperly specified `antModel` input, where one factor is defined across multiple lines. Your situation is not this one.
2. An improperly (or un-) specified model specification `lavaan.model.specs`. I believe yours is related to this issue. I think lavaan changed their specifications and basically broke the way I was calling for a CFA by default.

(1) is beyond the scope of this issue for now, but I believe the changes I made have fixed the issue you were seeing. Please reinstall the `bugfix` branch and let me know if any other errors come up!

**Comment by AnthonyRaborn** [comment]
Recent merge into main with #18 should have fixed this issue--it runs on my machine as expected with default `lavaan.model.specs`.
