### ISSUE TITLE
more lavaan 0.6-18 issues

### ISSUE THREAD

**Issue by yrosseel** [AnthonyRaborn/ShortForm#21]
In running the revdep checks again (using 0.5.4), I now get two (other) issues when running the tests (using lavaan 0.6-18). This is the output:
```
══ Failed tests ════════════════════════════════════════════════════════════════
── Failure ('test-simulated_annealing_internals.R:355:5'): selectionFunction accurately chooses between the best of two models ──
`selectionFunction(...)` produced no output
── Failure ('test-simulated_annealing_internals.R:368:5'): selectionFunction accurately chooses between the best of two models ──
selectionFunction(...) not equal to `currentBadModel`.
target is NULL, current is modelCheck

[ FAIL 2 | WARN 0 | SKIP 0 | PASS 50 ]
Error: Test failures
```
Maybe this is related to the new warning/error messages from lavaan? (But they did not change since I reported the previous issue).

**Comment by yrosseel** [comment]
My colleague (Luc De Wilde) suggested the following replacement for the `modelWarningCheck' function:

```{r}
modelWarningCheck <- function(expr, modelSyntax)
{
  warn <- err <- "none"
  value <- withCallingHandlers(tryCatch(expr, error = function(e) {
    err <<- append(err, e.message)
    NULL
  }), warning = function(w) {
    warn <<- append(warn, e.message)
    invokeRestart("muffleWarning")
  })
  new("modelCheck", model.output = value, warnings = warn,
      errors = err, model.syntax = modelSyntax)
}
```

Could you check if this resolves the problems?  (But make sure you are testing with the github version of lavaan: 0.6-18).

As this is blocking the CRAN update of lavaan 0.6-18, I would be very grateful if you could fix this ASAP and submit to CRAN.

**Comment by lucdw** [comment]
I saw I made a little error in suggested code: the first 'append' should have e$message as second argument, the second 'append' should have w$message as second argument.

**Comment by AnthonyRaborn** [comment]
Latest commit should fix these issues, thank you for the help in identifying where they were coming from. I will update again and close the issue once the newest ShortForm is on CRAN. 

#22

**Comment by AnthonyRaborn** [comment]
@yrosseel CRAN has accepted the release, please let me know if that doesn't solve the upstream issues! Thank you and @lucdw for the fix.

**Comment by yrosseel** [comment]
Wonderful. Thanks a lot!
