### ISSUE TITLE
Error in if (file == "") file <- stdin() else { :    the condition has length > 1

### ISSUE THREAD

**Issue by Mosen111** [AnthonyRaborn/ShortForm#23]
hello. i keep getting this error which I do not understand: "Error in if (file == "") file <- stdin() else { : 
  the condition has length > 1". can you please let me know what the problem is? I really appreciate any help you can provide. 

list.items <- list(c(
  "BAL1", "BAL2", "BAL3", "BAL4", "BAL5",
  "BAL6", "BAL7", "BAL8", "BAL9"),
  c("MOD1", "MOD2", "MOD3", "MOD4", "MOD5", "MOD6",
  "MOD7", "MOD8", "MOD9", "MOD10", "MOD11"), 
  c("LAPA1", "LAPA2", "LAPA3", "LAPA4", "LAPA5",
  "LAPA6", "LAPA7", "LAPA8", "LAPA9", "LAPA10",
  "LAPA11", "LAPA12"))

initial.MplusAutomation.model <- MplusAutomation::mplusObject(
  MODEL = "F1 BY BAL1 BAL2 BAL3 BAL4 BAL5
BAL6 BAL7 BAL8 BAL9;
F2 by  MOD1 MOD2 MOD3 MOD4 MOD5
MOD6 MOD7 MOD8 MOD9 MOD10 MOD11;
F3 by LAPA1 LAPA2 LAPA3 LAPA4 LAPA5 LAPA6 LAPA7
LAPA8 LAPA9 LAPA10 LAPA11 LAPA12;",
  ANALYSIS = "ESTIMATOR = MLR;",
  VARIABLE =  "USEVARIABLE = BAL1 BAL2 BAL3 BAL4 BAL5 
BAL6 BAL7 BAL8 BAL9 MOD1 MOD2 MOD3 MOD4 MOD5 
MOD6 MOD7 MOD8 MOD9 MOD10 MOD11 LAPA1 LAPA2 
LAPA3 LAPA4 LAPA5 LAPA6 LAPA7 LAPA8 LAPA9 LAPA10
LAPA11 LAPA12;",
  OUTPUT = "stdyx;",
  rdata = data)

finalShortForm <- antcolony.mplus(
  ants = 5, evaporation = 0.9,
  mplus = initial.MplusAutomation.model, list.items = list.items, full = 32,
  i.per.f = c(6, 6, 6), factors = c("F1","F2", "F3"), steps = 5, max.run = 30, resultfile = T, 
  min.CFI = 0.95, min.TLI = 0.95, max.RMSEA = 0.06)

**Comment by AnthonyRaborn** [comment]
I don't have the ability to test the MPlus function as I no longer have access to the program, but I think you need to define a results file as a character value of the file name; right now, you have specified `resultsfile = T` which is a logical and should be what's causing the issue. If you replace that with something like `resultsfile = 'results.txt'`, does that allow the function to run without issue?

**Comment by Mosen111** [comment]
thanks a lot for your reply. doing so resulted in a new error:
"Error in antcolony.mplus(ants = 5, evaporation = 0.9, mplus = initial.MplusAutomation.model,  : 
  unused argument (resultsfile = "results.txt")"


Nothing else worked, so i gave up on antcolony.mplus and tested it with antcolony.lavaan instead and it worked. thank you a lot for the help.
