### ISSUE TITLE
Several Random Questions

### ISSUE THREAD

**Issue by atjebb** [AnthonyRaborn/ShortForm#3]
For others who might use this package, here are some questions that I asked A. Raborn along with his answers.

Q: Within the antcolony functions, you can create 2 output files, a feedbackfile and summaryfile. What do 'count' and 'step' refer to (say, in the feedback file)?

A: Count refers to the number of iterations (models tested) since the best model has been updated. Step refers to the number of consecutive ants which selected the same model specification.

Q: Do I have it correct that the package only supports just one external criterion variable (either as predictor or outcome)? 

A:  No, the package supports any number of criterion variables. As implemented, the regression coefficients used are for the latent variable regression (hence the reference to them as gamma coefficients, instead of beta coefficients).

Q: It looks as though antcolony.lavaan can specify either 'gamma' or 'variance' as the performance measure through the 'pheromone.calculation' argument. If this argument isn't included, is 'gamma' the default (seems like this is so)? And is this argument available for antcolony.mplus? (in the documentation, the function doesn't seem to include this argument)

A: Yes, gamma is the default (I should specify so at `pheremone.calculation`, it seems). The antcolony.mplus function is not nearly as advanced as the antcolony.lavaan function--this is because antcolony.mplus is based on code from over a decade ago (Leite et al. 2008) with only minor modifications. Eventually, I would like to update the mplus functionality of the antcolony functions, but I have no timeline for package updates right now.

**Comment by AnthonyRaborn** [comment]
Thank you for posting this here!

For the third question, I have updated the documentation in the development branch to state that gamma is the default. However, the mplus functionality is still lagging and will probably lag unless there seems to be a stronger push for it in the userbase.
